### ISSUE TITLE
Hello, I have an idea.

### ISSUE THREAD

**Issue by mozhuqing** [flysofast/image-anomaly-detection#1]
You can use SSIM CNN autoencoder method (improving unsupervised defect segmentation by applying structural simplicity to autoencoders and MVtec ad-a comprehensive real world dataset for unsupervised) to get better detection results.

**Comment by flysofast** [comment]
Hi, thank you for your paper references. Yes I will do that in the next experiment :)

**Comment by mozhuqing** [comment]
II revised it again on your network, but reported such an error. Is there any problem? I set the crop_ Size to 256.
class Autoencoder(nn.Module):
    def __init__(self):
        # super(autoencoder, self).__init__()
        super(Autoencoder,self).__init__()
        self.encoder = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=32, kernel_size=4, stride=2, padding=1), # image size 64
            nn.LeakyReLU(0.2,True),

            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1), # image size 32
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1), # image size is 32
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=4, stride=2, padding=1), # image size is 16
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, stride=1, padding=1), # Image size is 16
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=4, stride=2, padding=1), # image size 8
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=128, out_channels=64, kernel_size=3, stride=1, padding=1), # Image size 8
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=64, out_channels=32, kernel_size=3, stride=1, padding=1), #Image size is 8
            nn.LeakyReLU(0.2, True),

            # nn.Conv2d(32, 100, 3, stride=1, padding=1),

            nn.Conv2d(in_channels=32, out_channels=100, kernel_size=8, stride=1, padding=0), #Image size is 8
            nn.ReLU(),


        )


        self.decoder = nn.Sequential(
            nn.Conv2d(100, 32, 8, stride=1, padding=0),
            nn.LeakyReLU(0.2, True),

            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),

            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),

            nn.Conv2d(in_channels=128, out_channels=64, kernel_size=4, stride=2, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),

            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),

            nn.Conv2d(in_channels=64, out_channels=32, kernel_size=4, stride=2, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),

            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=2, mode ='nearest'),


            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.2, True),
            nn.Upsample(scale_factor=4, mode ='nearest'),



            nn.Conv2d(in_channels=32, out_channels=3, kernel_size=4, stride=2, padding=1),
            # nn.Sigmoid()
            nn.ReLU(True)
        )
#
    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x

**Comment by flysofast** [comment]
I don't see the error message? What kind of error did you get?

**Comment by mozhuqing** [comment]
Sorry, I forgot. This is the wrong one.
RuntimeError: The size of tensor a (566) must match the size of tensor b (246) at non-singleton dimension 3
  0%|          | 0/313 [00:08<?, ?it/s]

**Comment by flysofast** [comment]
Where is this happening? My guess is the output of your network has a dimension that doesn't match the input's. Therefore the loss calculation or the tensor concatenation in the process of saving result images couldn't take place.

**Comment by mozhuqing** [comment]
Yes, I think so. I see your update. Your model has added a new network, but the input channel parameter of bottleneckv5 network is 1. Can I change it to a color image based on your network?

**Comment by flysofast** [comment]
Yes, you can change the input channel parameter of the model to 3, but I haven't tested it for the rest of pipeline (evaluation, image saving,..) so there will probably other errors, so brace yourself :) . I will do some more later today when I have time.

**Comment by mozhuqing** [comment]
Thank you very much.

**Comment by mozhuqing** [comment]
Hello, I have a question. Why is the reconstructed image missing the details? For example, hazelnut, whose reconstruction details are fuzzy.

**Comment by mozhuqing** [comment]
I found a problem in the code. Paper mentioned that the output layer of encoder and decoder should use linear activation function. By modifying this function, I can make the image texture information clear. You can try it. Are you Chinese? If so, we can add wechat. My wechat is mozhuqing.

**Comment by flysofast** [comment]
Hi. I don’t speak Chinese unfortunately. Can you add a screenshot of the result and/or the code that you use?

**Comment by mozhuqing** [comment]
![image](https://user-images.githubusercontent.com/37110091/75371675-22fc7b00-5902-11ea-93ce-769ca9e3fff4.png)

**Comment by mozhuqing** [comment]
![2](https://user-images.githubusercontent.com/37110091/75371830-7373d880-5902-11ea-8b4f-8a3aeec2c002.png)
![1](https://user-images.githubusercontent.com/37110091/75371839-75d63280-5902-11ea-8fa4-2c13196192f9.png)

**Comment by mozhuqing** [comment]
I uploaded the result graph, but I don't know why it can't be displayed. You can add my twitter account:QGT3x4JPGumNkzx

**Comment by mozhuqing** [comment]
I uploaded the result graph, but I don't know why it can't be displayed.

**Comment by flysofast** [comment]
Hi, I can see your results but they are a bit blurry, as you already said. I also got the same results for the first 100 epochs for model v2 or v4. However, if you trained the model for longer, you might get some results like this one (v2, epoch 350 on my computer)
<img width="345" alt="Screenshot 2020-02-27 at 10 41 32" src="https://user-images.githubusercontent.com/8488733/75426809-1140c500-594e-11ea-9350-5c44101147f9.png">

**Comment by mozhuqing** [comment]
Sorry, I can't see the picture you sent.。 when I trained to 200 epochs, the gradient burst. Later, we modify loss to limit the gradient to avoid bad points. Do you get similar results with nonlinear activation function?

**Comment by mozhuqing** [comment]
After training, I made prediction and found that the predicted image is almost the same as the input image. Why? Did this network cheat? I look forward to your reply in your spare time.
![QQ图片20200228231945](https://user-images.githubusercontent.com/37110091/75560840-e86d1c80-5a80-11ea-857f-6fb34ed43ab9.jpg)

**Comment by flysofast** [comment]
Hi sorry for the late reply. No I don't think the network is "cheating". If you use the v2 model, because that one has a large latent space, reconstructing such good quality images are possible. In fact, the images a sent you earlier showed even better result (without color distortion as it did in your result). The residual images in your case are probably very good, since the anomalous areas are brighter (higher error). You may want to normalize (map the min-max value range to 0-255 for better contrast) the residual image to see those area better.
For the v5 model, because of its narrow latent space, the reconstructed images will be blurry, I have also experienced the same thing. I haven't try the linear layers yet, but I would love to see how you did that part :)

**Comment by mozhuqing** [comment]
OK, thank you for your comments. Another problem is that when I train carpet, the prediction graph has no texture information, the same code, but can not get good results. Compared with the results mentioned on paper, it is quite different. Have you done the corresponding training on the data? Can you give me some advice?

**Comment by flysofast** [comment]
I think you can try different the data transformations, crop size, etc. Also the textures generally has more details than objects, I think you can also try larger latent space for better reconstruction.
